/*
Secure Build API

Testing BuildAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_BuildAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BuildAPIService AddBuild", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BuildAPI.AddBuild(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService GetBuildById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId int32

		resp, httpRes, err := apiClient.BuildAPI.GetBuildById(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService GetBuildOutputManifestById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId int32

		resp, httpRes, err := apiClient.BuildAPI.GetBuildOutputManifestById(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BuildAPIService GetSLSAById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var buildId int32

		resp, httpRes, err := apiClient.BuildAPI.GetSLSAById(context.Background(), buildId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
