/*
 * Secure Build API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildOutputManifest {
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<::std::collections::HashMap<String, crate::models::BuildOutput>>,
}

impl BuildOutputManifest {
    pub fn new() -> BuildOutputManifest {
        BuildOutputManifest {
            outputs: None,
        }
    }
}


