/*
 * Secure Build API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SlsaProvenanceV1Predicate : A structure representing the SLSA Provenance v1 Predicate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlsaProvenanceV1Predicate {
    #[serde(rename = "buildDefinition")]
    pub build_definition: Box<crate::models::SlsaProvenanceV1PredicateBuildDefinition>,
    #[serde(rename = "runDetails")]
    pub run_details: Box<crate::models::SlsaProvenanceV1PredicateRunDetails>,
}

impl SlsaProvenanceV1Predicate {
    /// A structure representing the SLSA Provenance v1 Predicate.
    pub fn new(build_definition: crate::models::SlsaProvenanceV1PredicateBuildDefinition, run_details: crate::models::SlsaProvenanceV1PredicateRunDetails) -> SlsaProvenanceV1Predicate {
        SlsaProvenanceV1Predicate {
            build_definition: Box::new(build_definition),
            run_details: Box::new(run_details),
        }
    }
}


