/*
 * Secure Build API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SlsaProvenanceV01 : Represents an In-Toto v1 statement.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlsaProvenanceV01 {
    #[serde(rename = "_type")]
    pub _type: String,
    #[serde(rename = "predicate")]
    pub predicate: Box<crate::models::SlsaProvenanceV1Predicate>,
    #[serde(rename = "predicateType")]
    pub predicate_type: String,
    #[serde(rename = "subject")]
    pub subject: Vec<crate::models::Subject>,
}

impl SlsaProvenanceV01 {
    /// Represents an In-Toto v1 statement.
    pub fn new(_type: String, predicate: crate::models::SlsaProvenanceV1Predicate, predicate_type: String, subject: Vec<crate::models::Subject>) -> SlsaProvenanceV01 {
        SlsaProvenanceV01 {
            _type,
            predicate: Box::new(predicate),
            predicate_type,
            subject,
        }
    }
}


