/*
 * Secure Build API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SlsaProvenanceV1PredicateRunDetailsBuilder : Identifies the build platform that executed the invocation, which is trusted to have correctly performed the operation and populated this provenance.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlsaProvenanceV1PredicateRunDetailsBuilder {
    #[serde(rename = "builderDependencies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub builder_dependencies: Option<Option<Vec<crate::models::SlsaProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner>>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<String>>,
}

impl SlsaProvenanceV1PredicateRunDetailsBuilder {
    /// Identifies the build platform that executed the invocation, which is trusted to have correctly performed the operation and populated this provenance.
    pub fn new(id: String) -> SlsaProvenanceV1PredicateRunDetailsBuilder {
        SlsaProvenanceV1PredicateRunDetailsBuilder {
            builder_dependencies: None,
            id,
            version: None,
        }
    }
}


