/*
 * Secure Build API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SlsaProvenanceV1PredicateBuildDefinition : A structure representing the build definition of the SLSA Provenance v1 Predicate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlsaProvenanceV1PredicateBuildDefinition {
    #[serde(rename = "buildType")]
    pub build_type: String,
    /// The parameters that are under external control, such as those set by a user or tenant of the build platform. They MUST be complete at SLSA Build L3, meaning that there is no additional mechanism for an external party to influence the build. (At lower SLSA Build levels, the completeness MAY be best effort.)\\nThe build platform SHOULD be designed to minimize the size and complexity of externalParameters, in order to reduce fragility and ease verification. Consumers SHOULD have an expectation of what “good” looks like; the more information that they need to check, the harder that task becomes.\\nVerifiers SHOULD reject unrecognized or unexpected fields within externalParameters.
    #[serde(rename = "externalParameters")]
    pub external_parameters: ::std::collections::HashMap<String, serde_json::Value>,
    /// Unordered collection of artifacts needed at build time. Completeness is best effort, at least through SLSA Build L3. For example, if the build script fetches and executes “example.com/foo.sh”, which in turn fetches “example.com/bar.tar.gz”, then both “foo.sh” and “bar.tar.gz” SHOULD be listed here.
    #[serde(rename = "internalParameters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub internal_parameters: Option<Option<::std::collections::HashMap<String, serde_json::Value>>>,
    /// Unordered collection of artifacts needed at build time. Completeness is best effort, at least through SLSA Build L3. For example, if the build script fetches and executes “example.com/foo.sh”, which in turn fetches “example.com/bar.tar.gz”, then both “foo.sh” and “bar.tar.gz” SHOULD be listed here.
    #[serde(rename = "resolvedDependencies", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resolved_dependencies: Option<Option<Vec<crate::models::SlsaProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner>>>,
}

impl SlsaProvenanceV1PredicateBuildDefinition {
    /// A structure representing the build definition of the SLSA Provenance v1 Predicate.
    pub fn new(build_type: String, external_parameters: ::std::collections::HashMap<String, serde_json::Value>) -> SlsaProvenanceV1PredicateBuildDefinition {
        SlsaProvenanceV1PredicateBuildDefinition {
            build_type,
            external_parameters,
            internal_parameters: None,
            resolved_dependencies: None,
        }
    }
}


