/*
 * Secure Build API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SlsaProvenanceV1PredicateRunDetailsMetadata : A structure representing the metadata of the SLSA Provenance v1 Predicate.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SlsaProvenanceV1PredicateRunDetailsMetadata {
    /// The timestamp of when the build completed.
    #[serde(rename = "finishedOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub finished_on: Option<Option<String>>,
    /// Identifies this particular build invocation, which can be useful for finding associated logs or other ad-hoc analysis. The exact meaning and format is defined by builder.id; by default it is treated as opaque and case-sensitive. The value SHOULD be globally unique.
    #[serde(rename = "invocationId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invocation_id: Option<Option<String>>,
    /// The timestamp of when the build started.
    #[serde(rename = "startedOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_on: Option<Option<String>>,
}

impl SlsaProvenanceV1PredicateRunDetailsMetadata {
    /// A structure representing the metadata of the SLSA Provenance v1 Predicate.
    pub fn new() -> SlsaProvenanceV1PredicateRunDetailsMetadata {
        SlsaProvenanceV1PredicateRunDetailsMetadata {
            finished_on: None,
            invocation_id: None,
            started_on: None,
        }
    }
}


