/*
Secure Build API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SLSAProvenanceV1PredicateRunDetailsBuilder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SLSAProvenanceV1PredicateRunDetailsBuilder{}

// SLSAProvenanceV1PredicateRunDetailsBuilder Identifies the build platform that executed the invocation, which is trusted to have correctly performed the operation and populated this provenance.
type SLSAProvenanceV1PredicateRunDetailsBuilder struct {
	BuilderDependencies []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner `json:"builderDependencies,omitempty"`
	Id string `json:"id"`
	Version NullableString `json:"version,omitempty"`
}

// NewSLSAProvenanceV1PredicateRunDetailsBuilder instantiates a new SLSAProvenanceV1PredicateRunDetailsBuilder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSLSAProvenanceV1PredicateRunDetailsBuilder(id string) *SLSAProvenanceV1PredicateRunDetailsBuilder {
	this := SLSAProvenanceV1PredicateRunDetailsBuilder{}
	this.Id = id
	return &this
}

// NewSLSAProvenanceV1PredicateRunDetailsBuilderWithDefaults instantiates a new SLSAProvenanceV1PredicateRunDetailsBuilder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSLSAProvenanceV1PredicateRunDetailsBuilderWithDefaults() *SLSAProvenanceV1PredicateRunDetailsBuilder {
	this := SLSAProvenanceV1PredicateRunDetailsBuilder{}
	return &this
}

// GetBuilderDependencies returns the BuilderDependencies field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) GetBuilderDependencies() []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner {
	if o == nil {
		var ret []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner
		return ret
	}
	return o.BuilderDependencies
}

// GetBuilderDependenciesOk returns a tuple with the BuilderDependencies field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) GetBuilderDependenciesOk() ([]SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner, bool) {
	if o == nil || IsNil(o.BuilderDependencies) {
		return nil, false
	}
	return o.BuilderDependencies, true
}

// HasBuilderDependencies returns a boolean if a field has been set.
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) HasBuilderDependencies() bool {
	if o != nil && IsNil(o.BuilderDependencies) {
		return true
	}

	return false
}

// SetBuilderDependencies gets a reference to the given []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner and assigns it to the BuilderDependencies field.
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) SetBuilderDependencies(v []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner) {
	o.BuilderDependencies = v
}

// GetId returns the Id field value
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) SetId(v string) {
	o.Id = v
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) GetVersion() string {
	if o == nil || IsNil(o.Version.Get()) {
		var ret string
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableString and assigns it to the Version field.
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) SetVersion(v string) {
	o.Version.Set(&v)
}
// SetVersionNil sets the value for Version to be an explicit nil
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *SLSAProvenanceV1PredicateRunDetailsBuilder) UnsetVersion() {
	o.Version.Unset()
}

func (o SLSAProvenanceV1PredicateRunDetailsBuilder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SLSAProvenanceV1PredicateRunDetailsBuilder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BuilderDependencies != nil {
		toSerialize["builderDependencies"] = o.BuilderDependencies
	}
	toSerialize["id"] = o.Id
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	return toSerialize, nil
}

type NullableSLSAProvenanceV1PredicateRunDetailsBuilder struct {
	value *SLSAProvenanceV1PredicateRunDetailsBuilder
	isSet bool
}

func (v NullableSLSAProvenanceV1PredicateRunDetailsBuilder) Get() *SLSAProvenanceV1PredicateRunDetailsBuilder {
	return v.value
}

func (v *NullableSLSAProvenanceV1PredicateRunDetailsBuilder) Set(val *SLSAProvenanceV1PredicateRunDetailsBuilder) {
	v.value = val
	v.isSet = true
}

func (v NullableSLSAProvenanceV1PredicateRunDetailsBuilder) IsSet() bool {
	return v.isSet
}

func (v *NullableSLSAProvenanceV1PredicateRunDetailsBuilder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSLSAProvenanceV1PredicateRunDetailsBuilder(val *SLSAProvenanceV1PredicateRunDetailsBuilder) *NullableSLSAProvenanceV1PredicateRunDetailsBuilder {
	return &NullableSLSAProvenanceV1PredicateRunDetailsBuilder{value: val, isSet: true}
}

func (v NullableSLSAProvenanceV1PredicateRunDetailsBuilder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSLSAProvenanceV1PredicateRunDetailsBuilder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


