/*
Secure Build API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SLSAProvenanceV1PredicateRunDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SLSAProvenanceV1PredicateRunDetails{}

// SLSAProvenanceV1PredicateRunDetails A structure representing the run details of the SLSA Provenance v1 Predicate.
type SLSAProvenanceV1PredicateRunDetails struct {
	Builder SLSAProvenanceV1PredicateRunDetailsBuilder `json:"builder"`
	// Additional artifacts generated during the build that are not considered the “output” of the build but that might be needed during debugging or incident response. For example, this might reference logs generated during the build and/or a digest of the fully evaluated build configuration.\\nIn most cases, this SHOULD NOT contain all intermediate files generated during the build. Instead, this SHOULD only contain files that are likely to be useful later and that cannot be easily reproduced.
	Byproducts []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner `json:"byproducts,omitempty"`
	Metadata NullableSLSAProvenanceV1PredicateRunDetailsMetadata `json:"metadata,omitempty"`
}

// NewSLSAProvenanceV1PredicateRunDetails instantiates a new SLSAProvenanceV1PredicateRunDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSLSAProvenanceV1PredicateRunDetails(builder SLSAProvenanceV1PredicateRunDetailsBuilder) *SLSAProvenanceV1PredicateRunDetails {
	this := SLSAProvenanceV1PredicateRunDetails{}
	this.Builder = builder
	return &this
}

// NewSLSAProvenanceV1PredicateRunDetailsWithDefaults instantiates a new SLSAProvenanceV1PredicateRunDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSLSAProvenanceV1PredicateRunDetailsWithDefaults() *SLSAProvenanceV1PredicateRunDetails {
	this := SLSAProvenanceV1PredicateRunDetails{}
	return &this
}

// GetBuilder returns the Builder field value
func (o *SLSAProvenanceV1PredicateRunDetails) GetBuilder() SLSAProvenanceV1PredicateRunDetailsBuilder {
	if o == nil {
		var ret SLSAProvenanceV1PredicateRunDetailsBuilder
		return ret
	}

	return o.Builder
}

// GetBuilderOk returns a tuple with the Builder field value
// and a boolean to check if the value has been set.
func (o *SLSAProvenanceV1PredicateRunDetails) GetBuilderOk() (*SLSAProvenanceV1PredicateRunDetailsBuilder, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Builder, true
}

// SetBuilder sets field value
func (o *SLSAProvenanceV1PredicateRunDetails) SetBuilder(v SLSAProvenanceV1PredicateRunDetailsBuilder) {
	o.Builder = v
}

// GetByproducts returns the Byproducts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SLSAProvenanceV1PredicateRunDetails) GetByproducts() []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner {
	if o == nil {
		var ret []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner
		return ret
	}
	return o.Byproducts
}

// GetByproductsOk returns a tuple with the Byproducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SLSAProvenanceV1PredicateRunDetails) GetByproductsOk() ([]SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner, bool) {
	if o == nil || IsNil(o.Byproducts) {
		return nil, false
	}
	return o.Byproducts, true
}

// HasByproducts returns a boolean if a field has been set.
func (o *SLSAProvenanceV1PredicateRunDetails) HasByproducts() bool {
	if o != nil && IsNil(o.Byproducts) {
		return true
	}

	return false
}

// SetByproducts gets a reference to the given []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner and assigns it to the Byproducts field.
func (o *SLSAProvenanceV1PredicateRunDetails) SetByproducts(v []SLSAProvenanceV1PredicateBuildDefinitionResolvedDependenciesInner) {
	o.Byproducts = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SLSAProvenanceV1PredicateRunDetails) GetMetadata() SLSAProvenanceV1PredicateRunDetailsMetadata {
	if o == nil || IsNil(o.Metadata.Get()) {
		var ret SLSAProvenanceV1PredicateRunDetailsMetadata
		return ret
	}
	return *o.Metadata.Get()
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SLSAProvenanceV1PredicateRunDetails) GetMetadataOk() (*SLSAProvenanceV1PredicateRunDetailsMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metadata.Get(), o.Metadata.IsSet()
}

// HasMetadata returns a boolean if a field has been set.
func (o *SLSAProvenanceV1PredicateRunDetails) HasMetadata() bool {
	if o != nil && o.Metadata.IsSet() {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given NullableSLSAProvenanceV1PredicateRunDetailsMetadata and assigns it to the Metadata field.
func (o *SLSAProvenanceV1PredicateRunDetails) SetMetadata(v SLSAProvenanceV1PredicateRunDetailsMetadata) {
	o.Metadata.Set(&v)
}
// SetMetadataNil sets the value for Metadata to be an explicit nil
func (o *SLSAProvenanceV1PredicateRunDetails) SetMetadataNil() {
	o.Metadata.Set(nil)
}

// UnsetMetadata ensures that no value is present for Metadata, not even an explicit nil
func (o *SLSAProvenanceV1PredicateRunDetails) UnsetMetadata() {
	o.Metadata.Unset()
}

func (o SLSAProvenanceV1PredicateRunDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SLSAProvenanceV1PredicateRunDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["builder"] = o.Builder
	if o.Byproducts != nil {
		toSerialize["byproducts"] = o.Byproducts
	}
	if o.Metadata.IsSet() {
		toSerialize["metadata"] = o.Metadata.Get()
	}
	return toSerialize, nil
}

type NullableSLSAProvenanceV1PredicateRunDetails struct {
	value *SLSAProvenanceV1PredicateRunDetails
	isSet bool
}

func (v NullableSLSAProvenanceV1PredicateRunDetails) Get() *SLSAProvenanceV1PredicateRunDetails {
	return v.value
}

func (v *NullableSLSAProvenanceV1PredicateRunDetails) Set(val *SLSAProvenanceV1PredicateRunDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableSLSAProvenanceV1PredicateRunDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableSLSAProvenanceV1PredicateRunDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSLSAProvenanceV1PredicateRunDetails(val *SLSAProvenanceV1PredicateRunDetails) *NullableSLSAProvenanceV1PredicateRunDetails {
	return &NullableSLSAProvenanceV1PredicateRunDetails{value: val, isSet: true}
}

func (v NullableSLSAProvenanceV1PredicateRunDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSLSAProvenanceV1PredicateRunDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


